[package]
name = "rust_gfx"
version = "0.1.0"
edition = "2018"

[dependencies]
winit = "~0.20.0"
gfx-hal = "0.6.0"
gfx-backend-vulkan = { version = "0.6.5", features = ["x11"] }
image = "~0.23.9"
serde = { version = "~1.0.115", features = ["derive"] }
bincode = "~1.3.1"
shaderc = "=0.6.2"
